name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm install

      - name: Install EAS CLI
        run: |
          npm install -g eas-cli@latest

      - name: Build Android APK with EAS
        run: |
          cd apps/mobile
          eas build --platform android --profile preview --non-interactive --wait
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download built APK
        run: |
          cd apps/mobile
          eas build:list --platform android --profile preview --status finished --limit 1 --json | jq -r '.[0].artifacts.buildUrl' | xargs wget -O app.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rheumaai-apk
          path: apps/mobile/app.apk
