- name: Check and create App.js if missing
  run: |
    cd apps/mobile
    if [ ! -f "App.js" ] && [ ! -f "App.tsx" ] && [ ! -f "App.jsx" ]; then
      echo "Creating basic App.js..."
      echo "import { StatusBar } from 'expo-status-bar';" > App.js
      echo "import { StyleSheet, Text, View } from 'react-native';" >> App.js
      echo "" >> App.js
      echo "export default function App() {" >> App.js
      echo "  return (" >> App.js
      echo "    <View style={styles.container}>" >> App.js
      echo "      <Text>RheumaAI App is working!</Text>" >> App.js
      echo "      <StatusBar style=\"auto\" />" >> App.js
      echo "    </View>" >> App.js
      echo "  );" >> App.js
      echo "}" >> App.js
      echo "" >> App.js
      echo "const styles = StyleSheet.create({" >> App.js
      echo "  container: {" >> App.js
      echo "    flex: 1," >> App.js
      echo "    backgroundColor: '#fff'," >> App.js
      echo "    alignItems: 'center'," >> App.js
      echo "    justifyContent: 'center'," >> App.js
      echo "  }," >> App.js
      echo "});" >> App.js
    fi
  working-directory: .
