name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm install

      - name: Create eas.json manually
        run: |
          cd apps/mobile
          echo '{
            "build": {
              "preview": {
                "android": {
                  "buildType": "apk",
                  "distribution": "internal"
                }
              },
              "production": {
                "android": {
                  "buildType": "apk"
                }
              }
            },
            "cli": {
              "appVersionSource": "remote",
              "requireCommit": false
            }
          }' > eas.json

      - name: Build Android APK with EAS
        run: |
          cd apps/mobile
          npx eas-cli@latest build --platform android --profile preview --non-interactive --wait
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Check build status
        run: |
          cd apps/mobile
          npx eas-cli@latest build:list --platform android --profile preview --status finished --limit 1
