name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java and Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: apps/mobile/package-lock.json

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm ci --no-audit

      - name: Setup Android environment
        uses: android-actions/setup-android@v2

      - name: Generate Android project
        run: |
          cd apps/mobile
          npx expo prebuild --platform android --clean --no-install
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Apply compatibility fixes
        run: |
          cd apps/mobile/android
          # Копируем подготовленные фикс-файлы
          cp ../../android-fixes/* .
          chmod +x gradlew

      - name: Build APK
        run: |
          cd apps/mobile/android
          ./gradlew assembleDebug --no-daemon --no-build-cache --warning-mode none
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rheumaai-apk
          path: apps/mobile/android/app/build/outputs/apk/debug/app-debug.apk
