name: Build with EAS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm install --legacy-peer-deps --force

      - name: Remove manual projectId from config
        run: |
          cd apps/mobile
          # Удаляем ручной projectId из app.config.js
          if grep -q "projectId" app.config.js; then
            sed -i '/eas: {/,/}/d' app.config.js
            echo "✅ Removed manual projectId from app.config.js"
          else
            echo "✅ No manual projectId found in app.config.js"
          fi

      - name: Clean EAS configuration
        run: |
          cd apps/mobile
          # Удаляем eas.json если существует
          rm -f eas.json
          echo "✅ Cleaned EAS configuration"

      - name: Initialize EAS Project
        run: |
          cd apps/mobile
          # Инициализируем EAS проект БЕЗ указания ID
          npx eas init --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Update EAS config with environment variables
        run: |
          cd apps/mobile
          # Создаем eas.json с env переменными
          cat > eas.json << EOF
          {
            "build": {
              "preview": {
                "android": {
                  "buildType": "apk",
                  "env": {
                    "SUPABASE_URL": "$SUPABASE_URL",
                    "SUPABASE_ANON_KEY": "$SUPABASE_ANON_KEY"
                  }
                }
              },
              "production": {
                "android": {
                  "buildType": "apk",
                  "env": {
                    "SUPABASE_URL": "$SUPABASE_URL",
                    "SUPABASE_ANON_KEY": "$SUPABASE_ANON_KEY"
                  }
                }
              }
            }
          }
          EOF

      - name: Build APK with EAS
        run: |
          cd apps/mobile
          npx eas build --platform android --non-interactive --no-wait
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
