name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm install

      - name: Fix Android configuration
        run: |
          cd apps/mobile/android
          chmod +x gradlew

      - name: Build APK with Gradle
        run: |
          cd apps/mobile/android
          ./gradlew assembleDebug --no-daemon --stacktrace
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rheumaai-apk
          path: apps/mobile/android/app/build/outputs/apk/debug/app-debug.apk

          .
