- name: Fix metro config
  run: |
    # Упрощаем metro.config.js
    echo "const { getDefaultConfig } = require('@expo/metro-config');" > apps/mobile/metro.config.js
    echo "module.exports = getDefaultConfig(__dirname);" >> apps/mobile/metro.config.js
  working-directory: .
