name: Build with EAS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Fix AJV dependencies
        run: |
          cd apps/mobile
          # Удаляем проблемные зависимости
          npm uninstall ajv ajv-keywords --save-dev
          # Устанавливаем совместимые версии
          npm install ajv@^8.12.0 --save-dev --legacy-peer-deps
          npm install ajv-keywords@^5.1.0 --save-dev --legacy-peer-deps
          # Чистим кэш
          npm cache clean --force

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm install --legacy-peer-deps --force

      - name: Build APK with EAS
        run: |
          cd apps/mobile
          eas build --platform android --non-interactive --no-wait
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
- name: Create placeholder assets
  run: |
    cd apps/mobile
    mkdir -p assets
    # Создаем минимальные PNG заглушки
    echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==" | base64 -d > assets/icon.png
    cp assets/icon.png assets/splash.png
    cp assets/icon.png assets/adaptive-icon.png
