name: Build Debug APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Debug Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
