name: Build with EAS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: apps/mobile/package-lock.json

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./apps/mobile

      - name: Build APK with EAS
        run: eas build --platform android --non-interactive --no-wait
        working-directory: ./apps/mobile
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
