- name: Apply CRITICAL Android fixes AFTER prebuild
  run: |
    cd apps/mobile/android
    
    # ПЕРЕЗАПИСЫВАЕМ Gradle версию на 7.6
    echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
    echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
    echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.6-all.zip" >> gradle/wrapper/gradle-wrapper.properties
    echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
    echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
    
    # ФИКСИМ hermesEnabled ошибку в app/build.gradle
    sed -i 's/hermesEnabled/hermesEnabled.toBoolean()/g' app/build.gradle
    
    # Отключаем toolchain
    echo "android.useAndroidX=true" > gradle.properties
    echo "android.enableJetifier=true" >> gradle.properties
    echo "org.gradle.java.installations.auto-detect=false" >> gradle.properties
    echo "org.gradle.java.installations.auto-download=false" >> gradle.properties
