- name: Check and create App.js if missing
  run: |
    cd apps/mobile
    echo "Checking for App files:"
    ls -la App.* || echo "No App files found"
    
    if [ ! -f "App.js" ] && [ ! -f "App.tsx" ] && [ ! -f "App.jsx" ]; then
      echo "Creating basic App.js..."
      cat > App.js << 'EOF'
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>RheumaAI App is working!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
EOF
      echo "✓ App.js created"
    else
      echo "✓ App file exists"
    fi
  working-directory: .
