name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm install

      - name: Install EAS CLI and jq
        run: |
          npm install -g eas-cli@latest
          sudo apt-get install -y jq

      - name: Initialize EAS project
        run: |
          cd apps/mobile
          eas init --non-interactive --id=default

      - name: Configure EAS project
        run: |
          cd apps/mobile
          echo '{
            "build": {
              "preview": {
                "android": {
                  "buildType": "apk"
                }
              },
              "production": {}
            },
            "cli": {
              "appVersionSource": "remote",
              "requireCommit": false
            }
          }' > eas.json

      - name: Build Android APK
        run: |
          cd apps/mobile
          eas build --platform android --profile preview --non-interactive --wait
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download built APK
        run: |
          cd apps/mobile
          BUILD_DATA=$(eas build:list --platform android --profile preview --status finished --limit 1 --json)
          BUILD_URL=$(echo $BUILD_DATA | jq -r '.[0].artifacts.buildUrl')
          wget -O app.apk $BUILD_URL

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rheumaai-apk
          path: apps/mobile/app.apk
