name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Cleanup previous processes
        run: |
          pkill -f "gradle" || true
          pkill -f "java" || true
          pkill -f "node" || true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Clean workspace
        run: |
          find . -name "*.lock" -delete
          find . -name "*.lockb" -delete
          rm -rf node_modules || true
          rm -rf apps/mobile/node_modules || true
          rm -rf apps/mobile/android/.gradle || true
          rm -rf ~/.npm || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          # УБИРАЕМ cache - он вызывает ошибку

      - name: Install dependencies with clean install
        run: |
          cd apps/mobile
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --no-audit --legacy-peer-deps --prefer-offline

      - name: Fix AJV module issue
        run: |
          cd apps/mobile
          npm install ajv@^8.12.0 --save-dev --legacy-peer-deps
          npm install ajv-keywords@^5.1.0 --save-dev --legacy-peer-deps

      - name: Generate Android project
        run: |
          cd apps/mobile
          npx expo prebuild --platform android --clean
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Force correct Gradle version
        run: |
          cd apps/mobile/android
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.6-all.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties

          echo "android.useAndroidX=true" > gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "org.gradle.java.installations.auto-detect=false" >> gradle.properties
          echo "org.gradle.java.installations.auto-download=false" >> gradle.properties

      - name: Fix harnessEnabled in build.gradle
        run: |
          cd apps/mobile/android
          sed -i 's/hennesEnabled/hennesEnabled.toBoolean()/g' app/build.gradle

      - name: Build APK with retry
        run: |
          cd apps/mobile/android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon --no-build-cache --warning-mode none --stacktrace || \
          (sleep 10 && ./gradlew clean && ./gradlew assembleRelease --no-daemon --no-build-cache --warning-mode none --stacktrace)
        timeout-minutes: 25

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rheumaai-apk
          path: apps/mobile/android/app/build/outputs/apk/release/*.apk

      - name: Final cleanup
        if: always()
        run: |
          pkill -f "gradle" || true
          pkill -f "java" || true
