name: Build with EAS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm install --legacy-peer-deps --force

      - name: Add correct EAS projectId to config
        run: |
          cd apps/mobile
          # Добавляем ПРАВИЛЬНЫЙ projectId в app.config.js
          if grep -q "projectId" app.config.js; then
            # Обновляем существующий projectId
            sed -i 's/"projectId": *"[^"]*"/"projectId": "d5601a8f-e0e8-4117-a7a8-701021f929c1"/' app.config.js
            echo "✅ Updated projectId in app.config.js"
          else
            # Добавляем новый projectId
            sed -i '/extra: {/a \      eas: {\n        projectId: "d5601a8f-e0e8-4117-a7a8-701021f929c1"\n      },' app.config.js
            echo "✅ Added projectId to app.config.js"
          fi

      - name: Initialize EAS Project with force
        run: |
          cd apps/mobile
          # Инициализируем EAS проект с force флагом
          npx eas init --non-interactive --force
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Update EAS config with environment variables
        run: |
          cd apps/mobile
          # Создаем eas.json с env переменными
          cat > eas.json << EOF
          {
            "build": {
              "preview": {
                "android": {
                  "buildType": "apk",
                  "env": {
                    "SUPABASE_URL": "$SUPABASE_URL",
                    "SUPABASE_ANON_KEY": "$SUPABASE_ANON_KEY"
                  }
                }
              },
              "production": {
                "android": {
                  "buildType": "apk",
                  "env": {
                    "SUPABASE_URL": "$SUPABASE_URL",
                    "SUPABASE_ANON_KEY": "$SUPABASE_ANON_KEY"
                  }
                }
              }
            }
          }
          EOF

      - name: Build APK with EAS
        run: |
          cd apps/mobile
          npx eas build --platform android --non-interactive --no-wait
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
