name: Build with EAS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Install dependencies
        run: |
          cd apps/mobile
          npm install --legacy-peer-deps --force

      - name: Create minimal EAS config
        run: |
          cd apps/mobile
          cat > eas.json << EOF
          {
            "cli": {
              "appVersionSource": "remote",
              "requireCommit": false
            },
            "build": {
              "preview": {
                "android": {
                  "buildType": "apk"
                }
              },
              "production": {
                "android": {
                  "buildType": "apk"
                }
              }
            },
            "submit": {
              "production": {}
            }
          }
          EOF

      - name: Initialize EAS project
        run: |
          cd apps/mobile
          npx eas init --non-interactive --force
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build APK with EAS
        run: |
          cd apps/mobile
          npx eas build --platform android --non-interactive --no-wait
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
