name: Build with EAS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          # УБРАНО кэширование из-за ошибки пути

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install --legacy-peer-deps --force
        working-directory: ./apps/mobile

      - name: Debug - Show environment info
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "EAS version: $(eas --version || echo 'EAS not installed')"
          echo "Current directory: $(pwd)"
          echo "Mobile directory contents:"
          ls -la apps/mobile/
          echo "NPM config cache:"
          npm config get cache

      - name: Build APK with EAS
        run: eas build --platform android --non-interactive --no-wait
        working-directory: ./apps/mobile
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
